#!/bin/bash

check-x509Authorities() {
  local expectedBundle=$1
  local containerName=$2
  local difference=""
  local x509Authorities=""

  # Check at most 30 times (with one second in between) that the server has
  # successfully synced down the local authorities.
  MAXCHECKS=30
  CHECKINTERVAL=1

  for ((i=1;i<=MAXCHECKS;i++)); do
    log-info "checking for x509 authorities propagation ($i of $MAXCHECKS max)..."

    x509Authorities=$(docker compose exec -T ${containerName} \
      /opt/spire/bin/spire-server bundle show -output json | jq '.x509_authorities' -c)

    difference=$(diff <(echo $expectedBundle) <(echo $x509Authorities))
    if [[ $difference == "" ]];
    then
      return 0
    fi

    log-info "difference: $difference"

    sleep "${CHECKINTERVAL}"
  done

  fail-now "Expected bundle: $expectedBundle \n got: $x509Authorities \n difference: $difference"
}

x509Authorities=$(docker compose exec -T root-server \
	/opt/spire/bin/spire-server bundle show -output json | jq '.x509_authorities' -c)

amountBundles=$(echo $x509Authorities | jq  length)

# TODO: update to 1....
if [[ $amountBundles -ne 1 ]];
then
	fail-now "Only one bundle expected at start"
fi

check-x509Authorities $x509Authorities "intermediateA-server"
check-x509Authorities $x509Authorities "intermediateB-server"
check-x509Authorities $x509Authorities "leafA-server"
check-x509Authorities $x509Authorities "leafB-server"

# Prepare authority
preparedAuthorityID=$(docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
	/opt/spire/bin/spire-server \
	localauthority x509 prepare -output json | jq .prepared_authority.authority_id)

# Verify that the prepared authority
searching="X509 CA prepared.*local_authority_id=${preparedAuthorityID}"
check-log-line root-server $searching

x509Authorities=$(docker compose exec -T root-server \
	/opt/spire/bin/spire-server bundle show -output json | jq '.x509_authorities' -c)
amountBundles=$(echo $x509Authorities | jq  length)
# TODO: update to 2....
if [[ $amountBundles -ne 2 ]];
then
	fail-now "Two bundles expected after prepare"
fi

check-x509Authorities $x509Authorities "intermediateA-server"
check-x509Authorities $x509Authorities "intermediateB-server"
check-x509Authorities $x509Authorities "leafA-server"
check-x509Authorities $x509Authorities "leafB-server"


