#!/bin/bash

preparedauthority=$(docker compose exec -t -e spire_server_fflags=forced_rotation root-server \
	/opt/spire/bin/spire-server \
	localauthority x509 show -output json | jq .prepared.authority_id -r)

echo "prepared authority: ${preparedauthority}"

activatedauthority=$(docker compose exec -t -e spire_server_fflags=forced_rotation root-server \
	/opt/spire/bin/spire-server \
	localauthority x509 activate -authorityid ${preparedauthority} -output json | jq .activated_authority.authority_id)

log-info "Activated authority: ${activateAuthority}"

searching="X509 CA activated*local_authority_id=${preparedAuthority}"
check-log-line root-server $searching
check-log-line root-server "Successfully rotated X.509 CA"

