#!/bin/bash

preparedauthority=$(docker compose exec -t -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
	/opt/spire/bin/spire-server \
	localauthority x509 show -output json | jq .prepared.authority_id -r)

activatedauthority=$(docker compose exec -t -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
	/opt/spire/bin/spire-server \
	localauthority x509 activate -authorityID ${preparedauthority} -output json | jq .activated_authority.authority_id)

log-info "Activated authority: ${activateAuthority}"

searching="X509 CA activated*local_authority_id=${preparedAuthority}"
check-log-line root-server $searching
check-log-line root-server "Successfully rotated X.509 CA"

