#!/bin/bash

NUMCHECKS=15
CHECKINTERVAL=2

verifyX509SVID() {
      local agent=$1
      local expectedAuthority=$2

      for ((i=1;i<=NUMCHECKS;i++)); do
        log-info "checking for SVID rotation ok $agent ($i of $MAXCHECKS max)..."
        # Write svid on disk
        docker compose exec -u 1001 -T $agent \
              /opt/spire/bin/spire-agent api fetch x509 \
              -socketPath /opt/spire/sockets/workload_api.sock \
              -write /tmp || fail-now "x509-SVID check failed"

        # Copy SVID
        docker cp $(docker compose ps -q $1):/tmp/svid.0.pem - | docker cp - $(docker compose ps -q $2):/opt/

        docker compose exec -u 1001 -T $2 \
              /opt/spire/bin/spire-agent api fetch x509 \
              -socketPath /opt/spire/sockets/workload_api.sock \
              -write /tmp || fail-now "x509-SVID check failed"

        docker compose exec -T $2 openssl verify -verbose -CAfile /tmp/bundle.0.pem -untrusted /opt/svid.0.pem /opt/svid.0.pem

        sleep "${CHECKINTERVAL}"
    done
}


# Function to check log lines
check_logs() {
      local component=$1
      shift
      for log in "$@"; do
            check-log-line ${component} "${log}"
      done
}


# Fetch old authority ID
oldAuthority=$(docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
      /opt/spire/bin/spire-server \
      localauthority x509 show -output json | jq .old.authority_id -r)

# Taint the old authority
docker compose exec -T -e SPIRE_SERVER_FFLAGS=forced_rotation root-server \
      /opt/spire/bin/spire-server \
      localauthority x509 taint -authorityID ${oldAuthority} -output json | jq .tainted_authority.authority_id

# Root server logs
check_logs root-server \
      "X\.509 authority tainted successfully|local_authority_id=${oldAuthority}" \
      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"

# Root agent logs
check_logs root-agent \
      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
      "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=3" \
      "Agent SVID is tainted by a root authority, forcing rotation"


# Verify workloads are rotated

# Intermediate A server and agent logs
check_logs intermediateA-server \
      "Current root CA is signed by a tainted upstream authority, preparing rotation" \
      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
check_logs intermediateA-agent \
      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
      "Scheduled rotation for SVID entries due to tainted X\.509 authorities|count=2" \
      "Agent SVID is tainted by a root authority, forcing rotation"

# Intermediate B server and agent logs
check_logs intermediateB-server \
      "Current root CA is signed by a tainted upstream authority, preparing rotation" \
      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
check_logs intermediateB-agent \
      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
      "Scheduled rotation for SVID entries due to tainted X.509 authorities|count=2" \
      "Agent SVID is tainted by a root authority, forcing rotation"

# Leaf A server and agent logs
check_logs leafA-server \
      "Current root CA is signed by a tainted upstream authority, preparing rotation" \
      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
check_logs leafA-agent \
      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
      "Scheduled rotation for SVID entries due to tainted X.509 authorities|count=1" \
      "Agent SVID is tainted by a root authority, forcing rotation"

# Leaf B server and agent logs
check_logs leafB-server \
      "Current root CA is signed by a tainted upstream authority, preparing rotation" \
      "Server SVID signed using a tainted authority, forcing rotation of the Server SVID"
check_logs leafB-agent \
      "New tainted X.509 authorities found|subject_key_ids=${oldAuthority}" \
      "Scheduled rotation for SVID entries due to tainted X.509 authorities|count=1" \
      "Agent SVID is tainted by a root authority, forcing rotation"

